Update setup.py
pip install csv_overview on ubuntu fails with this error:

    long_description=open('readme.md', 'rb').read(),
    IOError: [Errno 2] No such file or directory: 'readme.md'

This is due to case sensitivity.